- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
       - name: i am going to Install apache 
         yum:
           name: httpd
           state: present

       - name: starting my apache
         service:
           name: httpd
           state: started

       - name: copy index.html
         copy:
           src: ./index.html
           dest: /var/www/html/index.html
           mode: '0777'
